name: Deploy to Netlify

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths-ignore:
      - .github/workflows/deploy-pages.yml
      - '**/*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Netlify CLI
        run: |
          npm i -g netlify-cli@17

      - name: Netlify deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --prod --dir . --functions netlify/functions --site "$NETLIFY_SITE_ID"
